version: "3"

services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./public:/var/www/public
      - ./etc/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
    image: node
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./backend:/var/www
    working_dir: /var/www
    environment:
      - NODE_ENV=development
      - GOOGLE_CSE_CX=${GOOGLE_CSE_CX}
      - GOOGLE_CSE_API_KEY=${GOOGLE_CSE_API_KEY}
    command: npm run debug